name: "Terraform Deployment"
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  terraform:
    name:   tf-script-exec-job
    runs-on: ubuntu-latest

    steps:
      - name: TestStep01
        run: echo "Hello World"
